version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - export BUCKET=$BucketName
      - aws cloudformation package --template-file template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1ug0ni100pp7p --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
